version: "4.24.0"
services:
  linkshort:
    build: .
    container_name: linkshort
    image: jackseceng/linkshort
    ports:
    # - 80:80 # For production
    - 80:5000 # For debugging
    - 5432:5432 # For database