version: '3'

networks:
  ls-net:
    driver: bridge

services:
  redis-master:
    image: 'bitnami/redis:latest'
    networks:
      - ls-net
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password

  redis-replica:
    image: 'bitnami/redis:latest'
    networks:
      - ls-net
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password

  app:
    build: .
    networks:
      - ls-net

# docker-compose up --detach --scale redis-master=1 --scale redis-replica=3