---
version: '3'

networks:
  ls-net:
    driver: bridge

services:
  redis-master:
    image: 'bitnami/redis:latest'
    networks:
      - ls-net
    hostname: redis-master
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_USERNAME=${REDISUSER}
      - REDIS_PASSWORD=${REDISMASTER}

  redis-replica:
    image: 'bitnami/redis:latest'
    networks:
      - ls-net
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_USERNAME=${REDISUSER}
      - REDIS_MASTER_PASSWORD=${REDISMASTER}
      - REDIS_PASSWORD=${REDISREPLICA}

  app:
    build: .
    networks:
      - ls-net
    ports:
      - '6379' # REDIS Port
      - '8080:8080' # DEV Port
      - '80:80' # PROD Port
    environment:
      - REDIS_PASSWORD=${REDISMASTER}
      - REDIS_USERNAME=${REDISUSER}
