---
apiVersion: v1
kind: Service
metadata:
  name: linkshort-service
spec:
  selector:
    app: linkshort
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkshort-deployment
  labels:
    app: linkshort
spec:
  replicas: 5
  selector:
    matchLabels:
      app: linkshort
  template:
    metadata:
      labels:
        app: linkshort
    spec:
      containers:  
      - name: linkshort
        image: linkshort-app
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
