apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkshort-deploy
  labels:
    app: linkshort-app
spec:
  selector:
    matchLabels:
      app: linkshort-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: linkshort-app
    spec:
      containers:
      - name: linkshort-app
        image: jackseceng/linkshort:alpha
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"