apiVersion: v1
kind: Service
metadata:
  name: linkshort-app-service
spec:
  selector:
    app: linkshort-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkshort-app
spec:
  selector:
    matchLabels:
      app: linkshort-app
  replicas: 5
  template:
    metadata:
      labels:
        app: linkshort-app
    spec:
      containers:
      - name: linkshort-app
        image: docker.io/jackseceng/linkshort:beta
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        env:
        - name: REDIS_PASSWORD
          value: b3stp@$$w0rd
        - name: REDIS_USERNAME
          value: default

# kubectl create ns linkshort
# kubectl apply -n linkshort -f .\src\deployment.yaml
# kubectl get po -n linkshort 
# kubectl get svc -n linkshort
# minikube service -n linkshort linkshort-app-service

# https://www.youtube.com/watch?v=JmCn7k0PlV4 - DevOpsGuy 8s redis
