apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: linkshort
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: linkshort
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

## Use minikube locally: 
# minikube start

## Create and apply configuration:
# kubectl create ns linkshort
# kubectl apply -n linkshort -f .\src\storage-deployment.yaml

## Check for pod and service:
# kubectl get po -n linkshort 
# kubectl get svc -n linkshort

## Connect to service (Optional):
# minikube service -n linkshort redis-service

## Delete configuration:
# kubectl delete deployment redis -n linkshort
# kubectl delete service redis-service -n linkshort
# kubectl delete ns linkshort
