---
name: Code

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  Lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable