---
name: Commit

on:
  pull_request:
    branches:
        - main

jobs:
  Check-for-Conventional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webiny/ensure-conventional-commits@v1.3.0
        name: Ensure conventional commits
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            allowed-commit-types: "feat,fix,refactor,docs"
