---
name: Conventional Commits

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  main:
    name: Validate PR title
    if: ${{ (github.actor != 'renovate[bot]') && (github.actor != 'snyk-bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
