name: Docker

on:
  push:
    branches:
      - main

permissions:
  read-all

jobs:
  docker:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@e5daf5da4ebfd37300852e88eac67cc6ad147f38
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6a25f988bdfa969e96a38fc9f843ea31e0b5df27
      -
        name: Build and push
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        with:
          push: true
          tags: jackseceng/linkshort:latest