---
name: Linter

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    name: Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Lint Codebase
        uses: super-linter/super-linter/slim@ae844193ed3e200e74ca4b0a523b7d61956720cb
        env:
          DEFAULT_BRANCH: origin/main
          # To report GitHub Actions status checks
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: true
          VALIDATE_CHECKOV: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_HTML: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_YAML: true
          # To find and set more language specific linters
          # Fing VALIDATE_ALL_CODEBASE on this page:
          # https://github.com/super-linter/super-linter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}