name: "Snyk Python Scan"

on:
  push:
    branches: ["main" ]
    paths: ['**.py', '.github/workflows/snyk-py.yml']
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@4a528b5c534bb771b6e3772656a8e0e9dc902f8b
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@86b04fb0e47484f7282357688f21d5d0e32175fe
        with:
          sarif_file: snyk.sarif
