---
name: Trivy

on:
  pull_request:
    branches:
      - main

permissions:
  read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Build Image
        run: docker build -t docker.io/jackseceng/linkshort:${{ github.sha }} .
      - name: Test for Vulnerabilities
        uses: aquasecurity/trivy-action@a11da62073708815958ea6d84f5650c78a3ef85b
        with:
          image-ref: 'docker.io/jackseceng/linkshort:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
