---
name: Trivy

on:
  pull_request:
    branches:
        - main

permissions:
  read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Build Image
        run: docker build -t docker.io/jackseceng/linkshort:${{ github.sha }} .
      - name: Test for Vulnerabilities
        uses: aquasecurity/trivy-action@a11da62073708815958ea6d84f5650c78a3ef85b
        with:
          image-ref: 'docker.io/jackseceng/linkshort:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'